version: "3.7"

services:
  mongo:
    image: mongo:4.4.4
    container_name: mongo_todolist
    command: mongod --port 27018
    ports:
      - "27018:27018"
    networks:
      internal:
        ipv4_address: 172.16.238.20

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: elasticsearch_todolist
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      internal:
        ipv4_address: 172.16.238.10


volumes:
  elasticsearch-data:
    driver: local

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"